package BufferApp;


/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* martes 2 de abril de 2019 17H30' CEST
*/

public interface BufferOperations 
{
  boolean put (String elemento);
  boolean get (org.omg.CORBA.StringHolder elemento);
  boolean read (org.omg.CORBA.StringHolder elemento);
  boolean canPut ();
  void shutdown ();
} // interface BufferOperations
